# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 500)
        Form.setAutoFillBackground(False)
        self.formLayoutWidget = QtWidgets.QWidget(Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(9, 9, 581, 138))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.formLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.scale_edit = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.scale_edit.setFont(font)
        self.scale_edit.setObjectName("scale_edit")
        self.gridLayout.addWidget(self.scale_edit, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.longitude_edit = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.longitude_edit.setFont(font)
        self.longitude_edit.setObjectName("longitude_edit")
        self.gridLayout.addWidget(self.longitude_edit, 0, 1, 1, 1)
        self.width_edit = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.width_edit.setFont(font)
        self.width_edit.setObjectName("width_edit")
        self.gridLayout.addWidget(self.width_edit, 1, 1, 1, 1)
        self.show_map_button = QtWidgets.QPushButton(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.show_map_button.setFont(font)
        self.show_map_button.setObjectName("show_map_button")
        self.gridLayout.addWidget(self.show_map_button, 3, 0, 1, 2)
        self.map_label = QtWidgets.QLabel(Form)
        self.map_label.setGeometry(QtCore.QRect(0, 147, 600, 350))
        self.map_label.setObjectName("map_label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Отображение карты"))
        self.label_3.setText(_translate("Form", "Введите масштаб(5-10)"))
        self.label_2.setText(_translate("Form", "Введите широту:"))
        self.label.setText(_translate("Form", "Введите долготу:"))
        self.show_map_button.setText(_translate("Form", "Показать карту"))
        self.map_label.setText(_translate("Form", " "))
